service: graasp-openai
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  # the default is 6 seconds
  # note: api gateway current maximum is 30 seconds
  timeout: 25
  profile: ${self:custom.profiles.${sls:stage}}
  environment:
    OPENAI_API_KEY: ${file(./env.${sls:stage}.json):OPENAI_API_KEY}
    DEBUG: ${file(./env.${sls:stage}.json):DEBUG}
    MODEL: ${file(./env.${sls:stage}.json):MODEL}
    ORIGIN: ${file(./env.${sls:stage}.json):ORIGIN}
  httpApi:
    cors: true


functions:
  generate:
    handler: handler.generate
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements

custom:
  profiles:
    dev: graasp-development
    stage: graasp-staging
    prod: graasp-production
  # compile python deps in a dedicated environment
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-x86_64
